services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./services/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  backend:
    container_name: backend
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    #  mount the volumes so we can change code and hot reload
    volumes:
      - ./services/backend:/backend
    ports:
      - 8010:8010
    command: ["python", "manage.py", "run", "-h", "0.0.0.0", "-p", "8010"]
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://0.0.0.0:8010/healthcheck || exit 1"]
      interval: 1m30s
      start_period: 15s
      retries: 3
      timeout: 10s

  frontend:
    container_name: frontend
    build:
      context: ./services
      dockerfile: ./nginx/Dockerfile
      target: frontend-dependencies
    volumes:
      - ./services/frontend:/frontend
      - /frontend/node_modules
    command: npm run dev -- --host
